<a href="https://colab.research.google.com/github/isadorafranca/IPOGDS/blob/main/ML_AP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
# Carregar os arquivos CSV
train_data = pd.read_csv('train.csv')

In [5]:
formato = train_data.shape
print(formato)

(22083, 45)

In [4]:
# para exibir informações gerais do dataset
train_data.info(), train_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22083 entries, 0 to 22082
Data columns (total 45 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Patient Id                                        22083 non-null  object
 1   Patient Age                                       20656 non-null  float64
 2   Genes in mother's side                            22083 non-null  object
 3   Inherited from father                             21777 non-null  object
 4   Maternal gene                                     19273 non-null  object
 5   Paternal gene                                     22083 non-null  object
 6   Blood cell count (mcL)                            22083 non-null  float64
 7   Patient First Name                                22083 non-null  object
 8   Family Name                                       12392 non-null  object
 9   Father's name                                     22083 non-null  object
 10  Mother's age                                      16047 non-null  float64
 11  Father's age                                      16097 non-null  float64
 12  Institute Name                                    16977 non-null  object
 13  Location of Institute                             22083 non-null  object
 14  Status                                            22083 non-null  object
 15  Respiratory Rate (breaths/min)                    19934 non-null  object
 16  Heart Rate (rates/min                             19970 non-null  object
 17  Test 1                                            19956 non-null  float64
 18  Test 2                                            19931 non-null  float64
 19  Test 3                                            19936 non-null  float64
 20  Test 4                                            19943 non-null  float64
 21  Test 5                                            19913 non-null  float64
 22  Parental consent                                  19958 non-null  object
 23  Follow-up                                         19917 non-null  object
 24  Gender                                            19910 non-null  object
 25  Birth asphyxia                                    19944 non-null  object
 26  Autopsy shows birth defect (if applicable)        17691 non-null  object
 27  Place of birth                                    19959 non-null  object
 28  Folic acid details (peri-conceptional)            19966 non-null  object
 29  H/O serious maternal illness                      19931 non-null  object
 30  H/O radiation exposure (x-ray)                    19930 non-null  object
 31  H/O substance abuse                               19888 non-null  object
 32  Assisted conception IVF/ART                       19961 non-null  object
 33  History of anomalies in previous pregnancies      19911 non-null  object
 34  No. of previous abortion                          19921 non-null  float64
 35  Birth defects                                     19929 non-null  object
 36  White Blood cell count (thousand per microliter)  19935 non-null  float64
 37  Blood test result                                 19938 non-null  object
 38  Symptom 1                                         19928 non-null  float64
 39  Symptom 2                                         19861 non-null  float64
 40  Symptom 3                                         19982 non-null  float64
 41  Symptom 4                                         19970 non-null  float64
 42  Symptom 5                                         19930 non-null  float64
 43  Genetic Disorder                                  19937 non-null  object
 44  Disorder Subclass                                 19915 non-null  object
dtypes: float64(16), object(29)
memory usage: 7.6+ MB

(None,
   Patient Id  Patient Age Genes in mother's side Inherited from father  \
 0  PID0x6418          2.0                    Yes                    No
 1  PID0x25d5          4.0                    Yes                   Yes
 2  PID0x4a82          6.0                    Yes                    No
 3  PID0x4ac8         12.0                    Yes                    No
 4  PID0x1bf7         11.0                    Yes                    No

   Maternal gene Paternal gene  Blood cell count (mcL) Patient First Name  \
 0           Yes            No                4.760603            Richard
 1            No            No                4.910669               Mike
 2            No            No                4.893297           Kimberly
 3           Yes            No                4.705280            Jeffery
 4           NaN           Yes                4.720703            Johanna

   Family Name Father's name  ...  Birth defects  \
 0         NaN         Larre  ...            NaN
 1         NaN        Brycen  ...       Multiple
 2         NaN        Nashon  ...       Singular
 3   Hoelscher        Aayaan  ...       Singular
 4    Stutzman         Suave  ...       Multiple

    White Blood cell count (thousand per microliter) Blood test result  \
 0                                          9.857562               NaN
 1                                          5.522560            normal
 2                                               NaN            normal
 3                                          7.919321      inconclusive
 4                                          4.098210               NaN

   Symptom 1 Symptom 2 Symptom 3 Symptom 4  Symptom 5  \
 0       1.0       1.0       1.0       1.0        1.0
 1       1.0       NaN       1.0       1.0        0.0
 2       0.0       1.0       1.0       1.0        1.0
 3       0.0       0.0       1.0       0.0        0.0
 4       0.0       0.0       0.0       0.0        NaN

                                Genetic Disorder  \
 0   Mitochondrial genetic inheritance disorders
 1                                           NaN
 2  Multifactorial genetic inheritance disorders
 3   Mitochondrial genetic inheritance disorders
 4  Multifactorial genetic inheritance disorders

                      Disorder Subclass
 0  Leber's hereditary optic neuropathy
 1                      Cystic fibrosis
 2                             Diabetes
 3                       Leigh syndrome
 4                               Cancer

 [5 rows x 45 columns])

In [6]:
#resumo estatítico
train_data.describe()

,Patient Age,Blood cell count (mcL),Mother's age,Father's age,Test 1,Test 2,Test 3,Test 4,Test 5,No. of previous abortion,White Blood cell count (thousand per microliter),Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5
count,20656.000000,22083.000000,16047.000000,16097.000000,19956.0,19931.0,19936.0,19943.0,19913.0,19921.000000,19935.000000,19928.000000,19861.000000,19982.000000,19970.000000,19930.000000
mean,6.974148,4.898871,34.526454,41.972852,0.0,0.0,0.0,1.0,0.0,2.003062,7.486224,0.592483,0.551886,0.536233,0.497747,0.461917
std,4.319475,0.199663,9.852598,13.035501,0.0,0.0,0.0,0.0,0.0,1.411919,2.653393,0.491385,0.497313,0.498698,0.500007,0.498560
min,0.000000,4.092727,18.000000,20.000000,0.0,0.0,0.0,1.0,0.0,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.763109,26.000000,31.000000,0.0,0.0,0.0,1.0,0.0,1.000000,5.424703,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.000000,4.899399,35.000000,42.000000,0.0,0.0,0.0,1.0,0.0,2.000000,7.477132,1.000000,1.000000,1.000000,0.000000,0.000000
75%,11.000000,5.033830,43.000000,53.000000,0.0,0.0,0.0,1.0,0.0,3.000000,9.526152,1.000000,1.000000,1.000000,1.000000,1.000000
max,14.000000,5.609829,51.000000,64.000000,0.0,0.0,0.0,1.0,0.0,4.000000,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
#verificar a cardinalidade (valores vazios em colunas)
train_data.nunique()

Patient Id                                          22083
Patient Age                                            15
Genes in mother's side                                  2
Inherited from father                                   2
Maternal gene                                           2
Paternal gene                                           2
Blood cell count (mcL)                              22083
Patient First Name                                   2524
Family Name                                          6282
Father's name                                       16368
Mother's age                                           34
Father's age                                           45
Institute Name                                         27
Location of Institute                                  26
Status                                                  2
Respiratory Rate (breaths/min)                          2
Heart Rate (rates/min                                   2
Test 1                                                  1
Test 2                                                  1
Test 3                                                  1
Test 4                                                  1
Test 5                                                  1
Parental consent                                        1
Follow-up                                               2
Gender                                                  3
Birth asphyxia                                          4
Autopsy shows birth defect (if applicable)              3
Place of birth                                          2
Folic acid details (peri-conceptional)                  2
H/O serious maternal illness                            2
H/O radiation exposure (x-ray)                          4
H/O substance abuse                                     4
Assisted conception IVF/ART                             2
History of anomalies in previous pregnancies            2
No. of previous abortion                                5
Birth defects                                           2
White Blood cell count (thousand per microliter)    17277
Blood test result                                       4
Symptom 1                                               2
Symptom 2                                               2
Symptom 3                                               2
Symptom 4                                               2
Symptom 5                                               2
Genetic Disorder                                        3
Disorder Subclass                                       9
dtype: int64

In [8]:
#para visualizar valores vazios
train_data.isnull().sum()

Patient Id                                             0
Patient Age                                         1427
Genes in mother's side                                 0
Inherited from father                                306
Maternal gene                                       2810
Paternal gene                                          0
Blood cell count (mcL)                                 0
Patient First Name                                     0
Family Name                                         9691
Father's name                                          0
Mother's age                                        6036
Father's age                                        5986
Institute Name                                      5106
Location of Institute                                  0
Status                                                 0
Respiratory Rate (breaths/min)                      2149
Heart Rate (rates/min                               2113
Test 1                                              2127
Test 2                                              2152
Test 3                                              2147
Test 4                                              2140
Test 5                                              2170
Parental consent                                    2125
Follow-up                                           2166
Gender                                              2173
Birth asphyxia                                      2139
Autopsy shows birth defect (if applicable)          4392
Place of birth                                      2124
Folic acid details (peri-conceptional)              2117
H/O serious maternal illness                        2152
H/O radiation exposure (x-ray)                      2153
H/O substance abuse                                 2195
Assisted conception IVF/ART                         2122
History of anomalies in previous pregnancies        2172
No. of previous abortion                            2162
Birth defects                                       2154
White Blood cell count (thousand per microliter)    2148
Blood test result                                   2145
Symptom 1                                           2155
Symptom 2                                           2222
Symptom 3                                           2101
Symptom 4                                           2113
Symptom 5                                           2153
Genetic Disorder                                    2146
Disorder Subclass                                   2168
dtype: int64

In [14]:
# Corrigir tipos de dados das colunas numéricas que estão como objeto (texto)
numeric_columns = ["Respiratory Rate (breaths/min)", "Heart Rate (rates/min"]
for col in numeric_columns:
    train_data_cleaned[col] = pd.to_numeric(train_data_cleaned[col], errors="coerce")

In [13]:
# Remover colunas irrelevantes (nomes de pacientes e pais, ID, nome do instituto)
columns_to_drop = [
    "Patient Id", "Patient First Name", "Family Name", "Father's name",
    "Institute Name", "Location of Institute"
]
train_data_cleaned = train_data.drop(columns=columns_to_drop)

In [15]:
# Exibir as informações após a limpeza inicial
train_data_cleaned.info(), train_data_cleaned.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22083 entries, 0 to 22082
Data columns (total 39 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Patient Age                                       20656 non-null  float64
 1   Genes in mother's side                            22083 non-null  object
 2   Inherited from father                             21777 non-null  object
 3   Maternal gene                                     19273 non-null  object
 4   Paternal gene                                     22083 non-null  object
 5   Blood cell count (mcL)                            22083 non-null  float64
 6   Mother's age                                      16047 non-null  float64
 7   Father's age                                      16097 non-null  float64
 8   Status                                            22083 non-null  object
 9   Respiratory Rate (breaths/min)                    0 non-null      float64
 10  Heart Rate (rates/min                             0 non-null      float64
 11  Test 1                                            19956 non-null  float64
 12  Test 2                                            19931 non-null  float64
 13  Test 3                                            19936 non-null  float64
 14  Test 4                                            19943 non-null  float64
 15  Test 5                                            19913 non-null  float64
 16  Parental consent                                  19958 non-null  object
 17  Follow-up                                         19917 non-null  object
 18  Gender                                            19910 non-null  object
 19  Birth asphyxia                                    19944 non-null  object
 20  Autopsy shows birth defect (if applicable)        17691 non-null  object
 21  Place of birth                                    19959 non-null  object
 22  Folic acid details (peri-conceptional)            19966 non-null  object
 23  H/O serious maternal illness                      19931 non-null  object
 24  H/O radiation exposure (x-ray)                    19930 non-null  object
 25  H/O substance abuse                               19888 non-null  object
 26  Assisted conception IVF/ART                       19961 non-null  object
 27  History of anomalies in previous pregnancies      19911 non-null  object
 28  No. of previous abortion                          19921 non-null  float64
 29  Birth defects                                     19929 non-null  object
 30  White Blood cell count (thousand per microliter)  19935 non-null  float64
 31  Blood test result                                 19938 non-null  object
 32  Symptom 1                                         19928 non-null  float64
 33  Symptom 2                                         19861 non-null  float64
 34  Symptom 3                                         19982 non-null  float64
 35  Symptom 4                                         19970 non-null  float64
 36  Symptom 5                                         19930 non-null  float64
 37  Genetic Disorder                                  19937 non-null  object
 38  Disorder Subclass                                 19915 non-null  object
dtypes: float64(18), object(21)
memory usage: 6.6+ MB

(None,
    Patient Age Genes in mother's side Inherited from father Maternal gene  \
 0          2.0                    Yes                    No           Yes
 1          4.0                    Yes                   Yes            No
 2          6.0                    Yes                    No            No
 3         12.0                    Yes                    No           Yes
 4         11.0                    Yes                    No           NaN

   Paternal gene  Blood cell count (mcL)  Mother's age  Father's age    Status  \
 0            No                4.760603           NaN           NaN     Alive
 1            No                4.910669           NaN          23.0  Deceased
 2            No                4.893297          41.0          22.0     Alive
 3            No                4.705280          21.0           NaN  Deceased
 4           Yes                4.720703          32.0           NaN     Alive

    Respiratory Rate (breaths/min)  ...  Birth defects  \
 0                             NaN  ...            NaN
 1                             NaN  ...       Multiple
 2                             NaN  ...       Singular
 3                             NaN  ...       Singular
 4                             NaN  ...       Multiple

    White Blood cell count (thousand per microliter)  Blood test result  \
 0                                          9.857562                NaN
 1                                          5.522560             normal
 2                                               NaN             normal
 3                                          7.919321       inconclusive
 4                                          4.098210                NaN

    Symptom 1  Symptom 2  Symptom 3 Symptom 4 Symptom 5  \
 0        1.0        1.0        1.0       1.0       1.0
 1        1.0        NaN        1.0       1.0       0.0
 2        0.0        1.0        1.0       1.0       1.0
 3        0.0        0.0        1.0       0.0       0.0
 4        0.0        0.0        0.0       0.0       NaN

                                Genetic Disorder  \
 0   Mitochondrial genetic inheritance disorders
 1                                           NaN
 2  Multifactorial genetic inheritance disorders
 3   Mitochondrial genetic inheritance disorders
 4  Multifactorial genetic inheritance disorders

                      Disorder Subclass
 0  Leber's hereditary optic neuropathy
 1                      Cystic fibrosis
 2                             Diabetes
 3                       Leigh syndrome
 4                               Cancer

 [5 rows x 39 columns])

In [17]:
#revover colunas vazias
train_data_cleaned = train_data_cleaned.drop(columns=["Respiratory Rate (breaths/min)", "Heart Rate (rates/min"])

In [19]:
#exibir a quantidade de valores ausentes em cada coluna
missing_values = train_data_cleaned.isnull().sum()
missing_values[missing_values > 0]

Patient Age                                         1427
Inherited from father                                306
Maternal gene                                       2810
Mother's age                                        6036
Father's age                                        5986
Test 1                                              2127
Test 2                                              2152
Test 3                                              2147
Test 4                                              2140
Test 5                                              2170
Parental consent                                    2125
Follow-up                                           2166
Gender                                              2173
Birth asphyxia                                      2139
Autopsy shows birth defect (if applicable)          4392
Place of birth                                      2124
Folic acid details (peri-conceptional)              2117
H/O serious maternal illness                        2152
H/O radiation exposure (x-ray)                      2153
H/O substance abuse                                 2195
Assisted conception IVF/ART                         2122
History of anomalies in previous pregnancies        2172
No. of previous abortion                            2162
Birth defects                                       2154
White Blood cell count (thousand per microliter)    2148
Blood test result                                   2145
Symptom 1                                           2155
Symptom 2                                           2222
Symptom 3                                           2101
Symptom 4                                           2113
Symptom 5                                           2153
Genetic Disorder                                    2146
Disorder Subclass                                   2168
dtype: int64